// Regenerate src/seti/mapping.ts from VS Code's theme-seti icon theme.
//
//   node scripts/gen-seti.mjs
//
// The source `vs-seti-icon-theme.json` resolves mainstream file types
// (ts, js, json, md, css, ...) through `languageIds`, NOT `fileExtensions`
// (which only holds long-tail types). VS Code bridges extension -> languageId
// via each language extension's contribution; that table is not in the theme
// JSON, so we keep a curated bridge here and fold languageIds into a flat
// extension map. The emitted mapping.ts is therefore filename-only at runtime
// (no languageIds lookup needed): { fileNames, extensions, default }.

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const theme = JSON.parse(
  fs.readFileSync(path.join(here, "vs-seti-icon-theme.json"), "utf8"),
);

// "\\E001" (JSON) -> the PUA char at U+E001.
function glyphOf(defId) {
  const def = theme.iconDefinitions[defId];
  if (!def || !def.fontCharacter) return null;
  const m = /\\([0-9A-Fa-f]+)/.exec(def.fontCharacter);
  if (!m) return null;
  return String.fromCodePoint(parseInt(m[1], 16));
}

// Curated extension -> seti languageId. Covers the common dev types VS Code
// would resolve via its language layer. Long-tail types come from the theme's
// own fileExtensions map (overlaid below).
const EXT_TO_LANG = {
  ts: "typescript", mts: "typescript", cts: "typescript", "d.ts": "typescript",
  tsx: "typescriptreact",
  js: "javascript", mjs: "javascript", cjs: "javascript",
  jsx: "javascriptreact",
  json: "json", jsonc: "jsonc", jsonl: "jsonl",
  md: "markdown", markdown: "markdown",
  html: "html", htm: "html",
  css: "css", scss: "scss", sass: "sass", less: "less", styl: "stylus",
  py: "python", pyw: "python", pyi: "python",
  rs: "rust", go: "go",
  yaml: "yaml", yml: "yaml",
  sh: "shellscript", bash: "shellscript", zsh: "shellscript",
  c: "c", h: "c",
  cpp: "cpp", cc: "cpp", cxx: "cpp", hpp: "cpp", hh: "cpp",
  cs: "csharp", java: "java", kt: "kotlin", kts: "kotlin",
  swift: "swift", rb: "ruby", php: "php", pl: "perl", pm: "perl",
  lua: "lua", r: "r", dart: "dart",
  ex: "elixir", exs: "elixir", elm: "elm", hs: "haskell",
  ml: "ocaml", mli: "ocaml",
  clj: "clojure", cljs: "clojure", cljc: "clojure",
  coffee: "coffeescript",
  fs: "fsharp", fsi: "fsharp", fsx: "fsharp",
  groovy: "groovy", jl: "julia", m: "objective-c", mm: "objective-cpp",
  ps1: "powershell", psm1: "powershell", psd1: "powershell",
  sql: "sql", xml: "xml", vue: "vue",
  tex: "tex", latex: "latex",
  bat: "bat", cmd: "bat",
  properties: "properties", ini: "properties", cfg: "properties",
  tf: "terraform", tfvars: "terraform",
  bicep: "bicep", vala: "vala", hx: "haxe", haml: "haml",
  jade: "jade", pug: "jade", gradle: "gradle", gd: "godot",
  res: "rescript", resi: "rescript",
};

// extension -> glyph. languageIds-derived first, theme fileExtensions overlaid
// (explicit, long-tail entries win on conflict).
const extensions = {};
for (const [ext, lang] of Object.entries(EXT_TO_LANG)) {
  const g = glyphOf(theme.languageIds[lang]);
  if (g) extensions[ext] = g;
}
for (const [ext, defId] of Object.entries(theme.fileExtensions)) {
  const g = glyphOf(defId);
  if (g) extensions[ext] = g;
}

// exact filename -> glyph.
const fileNames = {};
for (const [name, defId] of Object.entries(theme.fileNames)) {
  const g = glyphOf(defId);
  if (g) fileNames[name] = g;
}

const def = glyphOf(theme.file);
if (!def) throw new Error("could not resolve default glyph");

const banner =
  "// GENERATED by scripts/gen-seti.mjs from VS Code's theme-seti. Do not edit by hand.\n" +
  "// Glyphs are Private Use Area chars rendered with the bundled `seti` webfont.\n";
const body =
  `export const fileNames: Record<string, string> = ${JSON.stringify(fileNames, null, 2)};\n\n` +
  `export const extensions: Record<string, string> = ${JSON.stringify(extensions, null, 2)};\n\n` +
  `export const defaultGlyph = ${JSON.stringify(def)};\n`;

const out = path.join(here, "..", "src", "seti", "mapping.ts");
fs.mkdirSync(path.dirname(out), { recursive: true });
fs.writeFileSync(out, banner + "\n" + body);
console.log(
  `wrote ${out}: ${Object.keys(fileNames).length} fileNames, ` +
    `${Object.keys(extensions).length} extensions, default ${JSON.stringify(def)}`,
);
