// The ACP launch catalog: agents Sway knows how to *start*, as distinct from
// agents Sway has *measured*.
//
// The distinction is the whole point of this module, and conflating the two is
// what lets a listing promise something nobody tested:
//
//   * A **supported harness** is an adapter (`crate::agents`). It has a launch,
//     a transport, a capability tier, and a `verified_against` naming the CLI
//     version its conventions were captured against. Settings > Agents shows one
//     card per adapter, and everything on that card is something Sway checked.
//   * A **catalog entry** is a launch command and a label, read off the official
//     ACP Registry. Nothing here has been run, so an entry carries no tier, no
//     capabilities and no version of Sway's own. It answers "what else speaks
//     this protocol", which is a genuinely useful question and a different one.
//
// So this module deliberately cannot produce an adapter. There is no
// `into_adapter`, and `catalog_entries` returns rows for display. A user who
// wants one of these writes the four-line TOML that ADAPTERS.md documents, which
// is also the moment somebody decides the entry is worth trusting.
//
// The data is generated by `dev/acp-catalog.mjs` and committed, not fetched at
// runtime: Sway adds no endpoint of its own, and a catalogue that needs the
// network would be empty exactly when a user is offline and wondering what their
// options are. That script's header carries the refresh story.

use serde::{Deserialize, Serialize};

/// One agent the registry describes, reduced to what Sway can act on.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct CatalogEntry {
    pub id: String,
    pub label: String,
    #[serde(default)]
    pub description: String,
    /// The version the **registry** pins, which is not a version Sway measured
    /// anything against. Carried because for an `npx` entry it is what would
    /// actually run.
    #[serde(default)]
    pub registry_version: Option<String>,
    #[serde(default)]
    pub website: Option<String>,
    pub program: String,
    #[serde(default)]
    pub args: Vec<String>,
    /// What the user needs for this launch to work: `npx`, `uvx`, or `on-path`
    /// for an agent they installed themselves.
    ///
    /// `on-path` is the one assumption the catalogue makes. The registry
    /// describes an archive to download and a path inside it; Sway downloads
    /// nothing, so what it can offer is the same command for a user who already
    /// has the binary. Named rather than hidden, so the UI says "if you have it"
    /// instead of implying Sway will fetch it.
    pub needs: String,
}

impl CatalogEntry {
    /// The launch as a user would type it, for display only.
    pub fn command(&self) -> String {
        if self.args.is_empty() {
            self.program.clone()
        } else {
            format!("{} {}", self.program, self.args.join(" "))
        }
    }
}

/// The committed catalog, provenance and all.
///
/// The provenance fields are not decoration: a list of unmeasured launch commands
/// with no origin and no date is exactly the thing that rots quietly, so the
/// commit it came from travels with it and the UI shows the date.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct AcpCatalog {
    pub source: String,
    pub registry_commit: String,
    #[serde(default)]
    pub generated_on: Option<String>,
    #[serde(default)]
    pub generated_by: String,
    pub entries: Vec<CatalogEntry>,
    /// Agents the **registry itself** reports as broken, id to reason, excluded
    /// from `entries`.
    ///
    /// Committed rather than merely skipped, so the shortfall against the
    /// upstream is visible instead of inferred from a count. Offering these would
    /// be worse than offering nothing: an entry here is *known broken by the
    /// people who curate the registry*, which is a far stronger claim than
    /// "untested by Sway".
    #[serde(default)]
    pub quarantined: std::collections::BTreeMap<String, String>,
}

const CATALOG_JSON: &str = include_str!("../catalog/acp-agents.json");

/// The catalog, or an empty one if the committed file ever fails to parse.
///
/// Empty rather than a panic: this is a list of suggestions, and a malformed
/// catalogue must not stop Sway from starting. The parse is pinned by a test, so
/// "empty" cannot be reached silently in a shipped build.
pub fn catalog() -> AcpCatalog {
    serde_json::from_str(CATALOG_JSON).unwrap_or_else(|e| {
        eprintln!("sway: ERROR parsing the bundled ACP catalog: {e}");
        AcpCatalog {
            source: String::new(),
            registry_commit: String::new(),
            generated_on: None,
            generated_by: String::new(),
            entries: Vec::new(),
            quarantined: Default::default(),
        }
    })
}

/// One catalog row as the UI needs it: the entry, plus whether Sway already
/// ships a measured adapter for the same agent.
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct CatalogRow {
    #[serde(flatten)]
    pub entry: CatalogEntry,
    pub command: String,
    /// The id of the adapter that already covers this agent, when one does.
    ///
    /// Matched on **either the adapter's id or its launch identity**, because
    /// each alone has a measured counterexample:
    ///
    ///   * *Program alone misses Gemini.* The registry launches it as
    ///     `npx -y @google/gemini-cli@0.55.1 --acp`, pinning a package version;
    ///     Sway's `gemini.toml` launches the `gemini` a user installed. Same
    ///     agent, two legitimate launches, no shared program.
    ///   * *Id alone misses Cursor.* The registry calls that entry `cursor` while
    ///     its binary is `cursor-agent`, so an adapter added under the binary's
    ///     name would read as uncovered.
    ///
    /// Either match is enough, because the cost of being wrong is asymmetric: a
    /// false match hides a suggestion the user did not need, while a missed one
    /// offers a second, unmeasured way to start an agent they already have
    /// properly.
    ///
    /// The identity is `launch_identity`, not the bare program, and Codex is why:
    /// it is the first bundled adapter whose chat binary is `npx`, and comparing
    /// programs would have made **every** `npx` row in the registry read as
    /// covered by Codex. A package runner's program name identifies the runner,
    /// never the agent.
    pub covered_by: Option<String>,
}

/// What a launch actually names, with the package runner seen through.
///
/// `npx -y @agentclientprotocol/codex-acp@1.2.0` is not a launch of `npx`, it is
/// a launch of `@agentclientprotocol/codex-acp`, and the pinned version is not
/// part of the identity: an adapter pinning 1.2.0 and a registry row pinning
/// 1.3.0 are the same agent. For anything else the program *is* the identity.
fn launch_identity(program: &str, args: &[String]) -> String {
    const RUNNERS: [&str; 3] = ["npx", "bunx", "pnpx"];
    if !RUNNERS.contains(&program) {
        return program.to_string();
    }
    args.iter()
        .find(|a| !a.starts_with('-'))
        .map(|pkg| {
            // Strip the version, keeping a leading `@scope/`: rfind, because
            // `@scope/name@1.2.0` has two `@` and only the last one is a pin.
            match pkg.rfind('@') {
                Some(i) if i > 0 => pkg[..i].to_string(),
                _ => pkg.clone(),
            }
        })
        .unwrap_or_else(|| program.to_string())
}

/// Catalog rows, each told whether an adapter already covers it.
#[tauri::command]
pub fn acp_catalog() -> Vec<CatalogRow> {
    let adapters = crate::agents::registry();
    catalog()
        .entries
        .into_iter()
        .map(|entry| {
            let wanted = launch_identity(&entry.program, &entry.args);
            let covered_by = adapters
                .iter()
                .find(|a| {
                    let chat = a
                        .chat
                        .as_ref()
                        .map(|c| launch_identity(&c.program, &c.base_args));
                    a.id == entry.id
                        || launch_identity(&a.program, &a.base_args) == wanted
                        || chat.as_deref() == Some(wanted.as_str())
                })
                .map(|a| a.id.clone());
            let command = entry.command();
            CatalogRow { entry, command, covered_by }
        })
        .collect()
}

/// The catalog's provenance, for the line that says where the list came from.
#[tauri::command]
pub fn acp_catalog_source() -> AcpCatalog {
    let mut c = catalog();
    // The entries are fetched separately by `acp_catalog`, which also answers
    // whether each is covered. Sending them twice would be the same list in two
    // shapes, and a caller reading the wrong one would show uncovered rows.
    c.entries = Vec::new();
    c
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The committed file parses, so `catalog()`'s empty fallback is unreachable
    /// in a shipped build rather than merely unlikely.
    #[test]
    fn the_committed_catalog_parses_and_carries_its_provenance() {
        let c = catalog();
        assert!(!c.entries.is_empty(), "the catalog ships entries");
        assert_eq!(c.source, "https://github.com/agentclientprotocol/registry");
        assert_eq!(c.registry_commit.len(), 40, "a full commit sha: {}", c.registry_commit);
        assert!(c.generated_on.is_some(), "and the date it was generated on");
        assert_eq!(c.generated_by, "dev/acp-catalog.mjs", "and the script that refreshes it");
    }

    /// Every entry is launchable as a program plus args, and says what it needs.
    /// A row with no command would be a name in a list with nothing behind it.
    #[test]
    fn every_entry_has_a_command_and_names_what_it_needs() {
        for e in catalog().entries {
            assert!(!e.program.is_empty(), "{}: a program", e.id);
            assert!(!e.label.is_empty(), "{}: a label", e.id);
            assert!(
                ["npx", "uvx", "on-path"].contains(&e.needs.as_str()),
                "{}: unknown needs `{}`",
                e.id,
                e.needs
            );
            // The one assumption the catalogue makes is stated per row, so a
            // `binary` entry cannot silently read as one Sway will fetch.
            if e.needs == "on-path" {
                assert!(!e.program.contains('/'), "{}: a bare program name", e.id);
            }
        }
    }

    /// `cursor-agent acp` specifically, because the plan names it: the registry
    /// describes Cursor as an archive to download, and what Sway can offer is the
    /// command for a user who already has it.
    #[test]
    fn the_catalog_offers_cursor_agent_acp() {
        let cursor = catalog()
            .entries
            .into_iter()
            .find(|e| e.id == "cursor")
            .expect("the registry lists Cursor");
        assert_eq!(cursor.command(), "cursor-agent acp");
        assert_eq!(cursor.needs, "on-path");
    }

    /// **The line between a catalog entry and a supported harness.**
    ///
    /// The catalog contributes nothing to the adapter registry, so nothing in it
    /// can reach Settings > Agents as a card, get a capability tier, or be
    /// launched. The agents that *are* supported are supported because a TOML
    /// ships for them, and the catalog says so rather than being the reason.
    #[test]
    fn a_catalog_entry_is_not_an_adapter() {
        let adapters: Vec<&str> = crate::agents::registry().iter().map(|a| a.id.as_str()).collect();
        let rows = acp_catalog();
        assert!(rows.len() > 30, "the catalog is the long list: {}", rows.len());

        // Far more entries than adapters: if the catalog were feeding the
        // registry, these two numbers would move together.
        assert!(
            rows.len() > adapters.len() * 5,
            "{} catalog rows against {} adapters",
            rows.len(),
            adapters.len()
        );

        // And the ones an adapter already covers say which, so the UI can offer
        // the measured harness instead of a second way to start the same agent.
        let covered: Vec<&str> = rows
            .iter()
            .filter(|r| r.covered_by.is_some())
            .map(|r| r.entry.id.as_str())
            .collect();
        assert!(covered.contains(&"opencode"), "opencode ships an adapter: {covered:?}");
        assert!(covered.contains(&"gemini"), "gemini ships an adapter: {covered:?}");
        assert!(
            covered.contains(&"codex-acp"),
            "codex.toml launches this exact package: {covered:?}"
        );
        assert!(
            !covered.contains(&"cursor"),
            "cursor ships none, so it stays an untested entry: {covered:?}"
        );
    }

    /// **The regression `launch_identity` exists to stop.**
    ///
    /// `codex.toml` is the first bundled adapter whose chat binary is `npx`, and
    /// the match used to compare programs. That would have made every `npx` row
    /// in the registry - the bulk of it - read as "already covered by Codex", so
    /// the catalog would have quietly stopped offering agents Sway has never
    /// measured. A package runner names the runner, never the agent.
    #[test]
    fn a_package_runner_does_not_cover_every_agent_launched_through_it() {
        let rows = acp_catalog();
        let npx: Vec<&CatalogRow> = rows.iter().filter(|r| r.entry.program == "npx").collect();
        assert!(npx.len() > 5, "the registry is mostly npx launches: {}", npx.len());

        let wrongly_covered: Vec<&str> = npx
            .iter()
            .filter(|r| r.covered_by.as_deref() == Some("codex") && r.entry.id != "codex-acp")
            .map(|r| r.entry.id.as_str())
            .collect();
        assert!(
            wrongly_covered.is_empty(),
            "these are npx launches of other agents, not of Codex: {wrongly_covered:?}"
        );
    }

    /// The identity sees through the runner and past the pin, and leaves an
    /// ordinary binary alone.
    #[test]
    fn launch_identity_names_the_package_not_the_runner() {
        let args = |v: &[&str]| v.iter().map(|s| s.to_string()).collect::<Vec<_>>();
        assert_eq!(
            launch_identity("npx", &args(&["-y", "@agentclientprotocol/codex-acp@1.2.0"])),
            "@agentclientprotocol/codex-acp"
        );
        // A pinned adapter and a differently pinned registry row are one agent.
        assert_eq!(
            launch_identity("npx", &args(&["-y", "@agentclientprotocol/codex-acp@9.9.9"])),
            launch_identity("npx", &args(&["-y", "@agentclientprotocol/codex-acp"])),
        );
        // An unscoped package keeps its whole name when it carries no pin.
        assert_eq!(launch_identity("npx", &args(&["-y", "some-agent"])), "some-agent");
        assert_eq!(launch_identity("npx", &args(&["-y", "some-agent@2.0.0"])), "some-agent");
        // Not a runner: the program is the identity, args or not.
        assert_eq!(launch_identity("opencode", &args(&["acp"])), "opencode");
        // A runner with nothing to run degrades to itself rather than panicking.
        assert_eq!(launch_identity("npx", &args(&["-y"])), "npx");
    }

    /// The provenance command sends no entries, so a caller cannot render an
    /// unannotated list that looks like the annotated one.
    #[test]
    fn the_provenance_command_carries_no_entries() {
        assert!(acp_catalog_source().entries.is_empty());
        assert!(!acp_catalog_source().registry_commit.is_empty());
    }

    /// **An agent the registry says is broken is not offered at all.**
    ///
    /// The catalogue's entries claim only "untested by Sway". A quarantined agent
    /// is a much stronger claim - the people curating the registry ran it and it
    /// failed - and putting one in the same list would launder that into the
    /// weaker one. Excluded, with the upstream's own reasons carried alongside so
    /// "why is X missing" has an answer.
    #[test]
    fn an_agent_the_registry_quarantines_is_not_offered() {
        let c = catalog();
        assert!(!c.quarantined.is_empty(), "the registry publishes a quarantine list");
        for (id, reason) in &c.quarantined {
            assert!(
                !c.entries.iter().any(|e| &e.id == id),
                "{id} is quarantined ({reason}) and must not be offered"
            );
            assert!(!reason.is_empty(), "{id}: quarantined for a stated reason");
        }
    }
}
