// The ACP launch catalog: agents Sway knows how to *start*, as distinct from
// agents Sway has *measured*.
//
// The distinction is the whole point of this module, and conflating the two is
// what lets a listing promise something nobody tested:
//
//   * A **supported harness** is an adapter (`crate::agents`). It has a launch,
//     a transport, a capability tier, and a `verified_against` naming the CLI
//     version its conventions were captured against. Settings > Agents shows one
//     card per adapter, and everything on that card is something Sway checked.
//   * A **catalog entry** is a launch command and a label, read off the official
//     ACP Registry. Nothing here has been run, so an entry carries no tier, no
//     capabilities and no version of Sway's own. It answers "what else speaks
//     this protocol", which is a genuinely useful question and a different one.
//
// So this module deliberately cannot produce an adapter. There is no
// `into_adapter`, and `catalog_entries` returns rows for display. A user who
// wants one of these writes the four-line TOML that ADAPTERS.md documents, which
// is also the moment somebody decides the entry is worth trusting.
//
// **Installing one does not change that.** `crate::install` can fetch the binary
// an entry names, and an installed agent is still an untested entry: it has a
// path on disk and nothing else. The two facts are kept in two modules and two
// commands so a row cannot quietly acquire a tier by being downloaded.
//
// The data is generated by `dev/acp-catalog.mjs` and committed, not fetched at
// runtime: Sway adds no endpoint of its own, and a catalogue that needs the
// network would be empty exactly when a user is offline and wondering what their
// options are. That script's header carries the refresh story.

use std::collections::BTreeMap;

use serde::{Deserialize, Serialize};

/// One agent the registry describes, reduced to what Sway can act on.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct CatalogEntry {
    pub id: String,
    pub label: String,
    #[serde(default)]
    pub description: String,
    /// The version the **registry** pins, which is not a version Sway measured
    /// anything against. Carried because for an `npx` entry it is what would
    /// actually run.
    #[serde(default)]
    pub registry_version: Option<String>,
    #[serde(default)]
    pub website: Option<String>,
    pub program: String,
    #[serde(default)]
    pub args: Vec<String>,
    /// What the user needs for this launch to work: `npx`, `uvx`, `install` for
    /// an agent Sway can fetch, or `on-path` for one it cannot.
    ///
    /// `on-path` is the fallback, not the default: it means the registry
    /// described a binary distribution Sway could make nothing of, so the only
    /// honest offer left is the same command for a user who already has it.
    pub needs: String,
    /// Every platform the registry publishes a download for, keyed exactly as it
    /// keys them (`darwin-aarch64`, `windows-x86_64`).
    ///
    /// Carried whole rather than reduced to this machine's entry, because the
    /// map is the only thing that can tell "there is no build for your
    /// architecture" apart from "this agent ships no binaries at all". Measured
    /// 2026-08-14, `kimi` is the live example: `darwin-aarch64` and both Linux
    /// targets, no `darwin-x86_64`.
    #[serde(default)]
    pub builds: BTreeMap<String, Build>,
    /// The **registry's own** probe of this agent, when it published one.
    #[serde(default)]
    pub published_capabilities: Option<PublishedCapabilities>,
}

/// One platform's download, exactly as the registry publishes it.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all(serialize = "camelCase"))]
pub struct Build {
    pub archive: String,
    /// The checksum, when the publisher supplies one.
    ///
    /// `Option` because it is genuinely optional upstream, not because parsing
    /// might fail: measured 2026-08-14, only 9 of the 17 binary agents publish
    /// one for darwin. An unverified download is a fact the user is told, and
    /// `None` is how it stays tellable.
    #[serde(default)]
    pub sha256: Option<String>,
    /// The path inside the archive, as the registry writes it (`./bin/devin`).
    pub cmd: String,
    #[serde(default)]
    pub args: Vec<String>,
    /// Environment the agent needs to speak ACP at all, when it needs any.
    /// `vtcode` is the measured example, with `VT_ACP_ENABLED=1`.
    #[serde(default)]
    pub env: BTreeMap<String, String>,
}

/// What the registry's own capability probe answered for one agent.
///
/// **Not a tier.** A tier is `src/utils/chatCapabilities.ts`, keyed on a
/// transport Sway implements and backed by measurements Sway took. This is a
/// third party's probe of somebody else's binary on a date, carried under a name
/// that says so, and folding the two would let an untested row inherit claims
/// nobody in this repo stands behind. Every field is `Option` because the file
/// sits in a dot-directory covered by no published schema, so "the matrix did
/// not say" has to stay distinguishable from "the matrix said no".
///
/// Read from the committed file in `snake_case` and sent to the frontend in
/// `camelCase`, which is the repo's wire convention; the two are stated
/// separately here rather than left to a container default that only happens to
/// be right in one direction.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all(serialize = "camelCase"))]
pub struct PublishedCapabilities {
    #[serde(default)]
    pub initialize: Option<String>,
    #[serde(default)]
    pub protocol_version: Option<u32>,
    #[serde(default)]
    pub load_session: Option<bool>,
    #[serde(default)]
    pub session_list: Option<bool>,
    #[serde(default)]
    pub session_fork: Option<bool>,
    #[serde(default)]
    pub session_resume: Option<bool>,
    #[serde(default)]
    pub session_stop: Option<bool>,
    #[serde(default)]
    pub set_model: Option<bool>,
}

/// Where the published capabilities came from, and when they were taken.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all(serialize = "camelCase"))]
pub struct MatrixSource {
    pub source: String,
    #[serde(default)]
    pub probed_on: Option<String>,
    #[serde(default)]
    pub agents_probed: u32,
}

impl CatalogEntry {
    /// The launch as a user would type it, for display only.
    pub fn command(&self) -> String {
        if self.args.is_empty() {
            self.program.clone()
        } else {
            format!("{} {}", self.program, self.args.join(" "))
        }
    }
}

/// The committed catalog, provenance and all.
///
/// The provenance fields are not decoration: a list of unmeasured launch commands
/// with no origin and no date is exactly the thing that rots quietly, so the
/// commit it came from travels with it and the UI shows the date.
#[derive(Debug, Clone, PartialEq, Eq, Deserialize)]
pub struct AcpCatalog {
    pub source: String,
    pub registry_commit: String,
    #[serde(default)]
    pub generated_on: Option<String>,
    #[serde(default)]
    pub generated_by: String,
    /// Where `published_capabilities` came from, or `None` when the generator
    /// could read no matrix. Optional at the type level for the same reason it is
    /// optional in the file: the catalogue is built either way.
    #[serde(default)]
    pub matrix_source: Option<MatrixSource>,
    pub entries: Vec<CatalogEntry>,
    /// Agents the **registry itself** reports as broken, id to reason, excluded
    /// from `entries`.
    ///
    /// Committed rather than merely skipped, so the shortfall against the
    /// upstream is visible instead of inferred from a count. Offering these would
    /// be worse than offering nothing: an entry here is *known broken by the
    /// people who curate the registry*, which is a far stronger claim than
    /// "untested by Sway".
    #[serde(default)]
    pub quarantined: std::collections::BTreeMap<String, String>,
}

const CATALOG_JSON: &str = include_str!("../catalog/acp-agents.json");

/// The catalog, or an empty one if the committed file ever fails to parse.
///
/// Empty rather than a panic: this is a list of suggestions, and a malformed
/// catalogue must not stop Sway from starting. The parse is pinned by a test, so
/// "empty" cannot be reached silently in a shipped build.
pub fn catalog() -> AcpCatalog {
    serde_json::from_str(CATALOG_JSON).unwrap_or_else(|e| {
        eprintln!("sway: ERROR parsing the bundled ACP catalog: {e}");
        AcpCatalog {
            source: String::new(),
            registry_commit: String::new(),
            generated_on: None,
            generated_by: String::new(),
            matrix_source: None,
            entries: Vec::new(),
            quarantined: Default::default(),
        }
    })
}

/// This machine, keyed the way the registry keys its `binary` distribution.
///
/// `None` on a target the registry has no vocabulary for, which is the honest
/// answer: an unknown key would match no build, and guessing one would offer a
/// download for somebody else's machine.
pub fn host_platform() -> Option<&'static str> {
    let os = match std::env::consts::OS {
        "macos" => "darwin",
        "linux" => "linux",
        "windows" => "windows",
        _ => return None,
    };
    let arch = match std::env::consts::ARCH {
        "aarch64" => "aarch64",
        "x86_64" => "x86_64",
        _ => return None,
    };
    Some(match (os, arch) {
        ("darwin", "aarch64") => "darwin-aarch64",
        ("darwin", "x86_64") => "darwin-x86_64",
        ("linux", "aarch64") => "linux-aarch64",
        ("linux", "x86_64") => "linux-x86_64",
        ("windows", "aarch64") => "windows-aarch64",
        _ => "windows-x86_64",
    })
}

/// What installing `entry` would fetch on `platform`.
///
/// Three answers, never two: a build, `NoBuildHere` when the agent ships
/// binaries but not for this machine, and `NotInstallable` when it ships none at
/// all. Collapsing the first two would turn "your architecture is unsupported"
/// into "this agent is an npx launch", which is a different sentence and a
/// different remedy.
pub enum HostBuild<'a> {
    Ready(&'a Build),
    NoBuildHere,
    NotInstallable,
}

pub fn build_for<'a>(entry: &'a CatalogEntry, platform: Option<&str>) -> HostBuild<'a> {
    if entry.builds.is_empty() {
        return HostBuild::NotInstallable;
    }
    match platform.and_then(|p| entry.builds.get(p)) {
        Some(b) => HostBuild::Ready(b),
        None => HostBuild::NoBuildHere,
    }
}

/// One catalog row as the UI needs it: the entry, plus whether Sway already
/// ships a measured adapter for the same agent.
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct CatalogRow {
    pub id: String,
    pub label: String,
    pub description: String,
    pub registry_version: Option<String>,
    pub website: Option<String>,
    pub needs: String,
    pub published_capabilities: Option<PublishedCapabilities>,
    /// The download for *this* machine, when there is one.
    pub build: Option<Build>,
    /// Set when the agent ships binaries but none for this machine's platform.
    /// Distinct from `build: None`, which an `npx` row also has.
    pub no_build_here: bool,
    pub command: String,
    /// The id of the adapter that already covers this agent, when one does.
    ///
    /// Matched on **either the adapter's id or its launch identity**, because
    /// each alone has a measured counterexample:
    ///
    ///   * *Program alone misses Gemini.* The registry launches it as
    ///     `npx -y @google/gemini-cli@0.55.1 --acp`, pinning a package version;
    ///     Sway's `gemini.toml` launches the `gemini` a user installed. Same
    ///     agent, two legitimate launches, no shared program.
    ///   * *Id alone misses Cursor.* The registry calls that entry `cursor` while
    ///     its binary is `cursor-agent`, so an adapter added under the binary's
    ///     name would read as uncovered.
    ///
    /// Either match is enough, because the cost of being wrong is asymmetric: a
    /// false match hides a suggestion the user did not need, while a missed one
    /// offers a second, unmeasured way to start an agent they already have
    /// properly.
    ///
    /// The identity is `launch_identity`, not the bare program, and Codex is why:
    /// it is the first bundled adapter whose chat binary is `npx`, and comparing
    /// programs would have made **every** `npx` row in the registry read as
    /// covered by Codex. A package runner's program name identifies the runner,
    /// never the agent.
    pub covered_by: Option<String>,
}

/// What a launch actually names, with the package runner seen through.
///
/// `npx -y @agentclientprotocol/codex-acp@1.2.0` is not a launch of `npx`, it is
/// a launch of `@agentclientprotocol/codex-acp`, and the pinned version is not
/// part of the identity: an adapter pinning 1.2.0 and a registry row pinning
/// 1.3.0 are the same agent. For anything else the program *is* the identity.
fn launch_identity(program: &str, args: &[String]) -> String {
    const RUNNERS: [&str; 3] = ["npx", "bunx", "pnpx"];
    if !RUNNERS.contains(&program) {
        return program.to_string();
    }
    args.iter()
        .find(|a| !a.starts_with('-'))
        .map(|pkg| {
            // Strip the version, keeping a leading `@scope/`: rfind, because
            // `@scope/name@1.2.0` has two `@` and only the last one is a pin.
            match pkg.rfind('@') {
                Some(i) if i > 0 => pkg[..i].to_string(),
                _ => pkg.clone(),
            }
        })
        .unwrap_or_else(|| program.to_string())
}

/// One catalog entry as a row, resolved against the adapters and a platform.
///
/// Takes the platform rather than reading it, so both darwin architectures are
/// answerable from one machine. Otherwise "does `darwin-x86_64` resolve" would be
/// a question only an Intel Mac could ask.
fn row_for(
    entry: CatalogEntry,
    adapters: &[crate::agents::AgentAdapter],
    platform: Option<&str>,
) -> CatalogRow {
    let wanted = launch_identity(&entry.program, &entry.args);
    let covered_by = adapters
        .iter()
        .find(|a| {
            let chat = a.chat.as_ref().map(|c| launch_identity(&c.program, &c.base_args));
            a.id == entry.id
                || launch_identity(&a.program, &a.base_args) == wanted
                || chat.as_deref() == Some(wanted.as_str())
        })
        .map(|a| a.id.clone());
    let (build, no_build_here) = match build_for(&entry, platform) {
        HostBuild::Ready(b) => (Some(b.clone()), false),
        HostBuild::NoBuildHere => (None, true),
        HostBuild::NotInstallable => (None, false),
    };
    CatalogRow {
        command: entry.command(),
        id: entry.id,
        label: entry.label,
        description: entry.description,
        registry_version: entry.registry_version,
        website: entry.website,
        needs: entry.needs,
        published_capabilities: entry.published_capabilities,
        build,
        no_build_here,
        covered_by,
    }
}

/// Catalog rows, each told whether an adapter already covers it and what
/// installing it would fetch here.
#[tauri::command]
pub fn acp_catalog() -> Vec<CatalogRow> {
    let adapters = crate::agents::registry();
    let platform = host_platform();
    catalog().entries.into_iter().map(|e| row_for(e, adapters, platform)).collect()
}

/// The catalog's provenance, for the line that says where the list came from.
///
/// A wire type of its own rather than the file's, because the two answer
/// different questions: the file is a list plus its origin, and this is the
/// origin alone. Sending the entries here as well would be the same list in two
/// shapes, and a caller reading the wrong one would show uncovered rows.
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct CatalogSource {
    pub source: String,
    pub registry_commit: String,
    pub generated_on: Option<String>,
    pub generated_by: String,
    pub matrix_source: Option<MatrixSource>,
    /// This machine, so a row saying "no build for your architecture" can name
    /// the architecture it means.
    pub host_platform: Option<String>,
}

#[tauri::command]
pub fn acp_catalog_source() -> CatalogSource {
    let c = catalog();
    CatalogSource {
        source: c.source,
        registry_commit: c.registry_commit,
        generated_on: c.generated_on,
        generated_by: c.generated_by,
        matrix_source: c.matrix_source,
        host_platform: host_platform().map(str::to_string),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The committed file parses, so `catalog()`'s empty fallback is unreachable
    /// in a shipped build rather than merely unlikely.
    #[test]
    fn the_committed_catalog_parses_and_carries_its_provenance() {
        let c = catalog();
        assert!(!c.entries.is_empty(), "the catalog ships entries");
        assert_eq!(c.source, "https://github.com/agentclientprotocol/registry");
        assert_eq!(c.registry_commit.len(), 40, "a full commit sha: {}", c.registry_commit);
        assert!(c.generated_on.is_some(), "and the date it was generated on");
        assert_eq!(c.generated_by, "dev/acp-catalog.mjs", "and the script that refreshes it");
    }

    /// Every entry is launchable as a program plus args, and says what it needs.
    /// A row with no command would be a name in a list with nothing behind it.
    #[test]
    fn every_entry_has_a_command_and_names_what_it_needs() {
        for e in catalog().entries {
            assert!(!e.program.is_empty(), "{}: a program", e.id);
            assert!(!e.label.is_empty(), "{}: a label", e.id);
            assert!(
                ["npx", "uvx", "install", "on-path"].contains(&e.needs.as_str()),
                "{}: unknown needs `{}`",
                e.id,
                e.needs
            );
            // `install` and `builds` are one claim said twice, so they cannot
            // disagree: a row offering an install with nothing to download would
            // be a button that fails when pressed.
            assert_eq!(
                e.needs == "install",
                !e.builds.is_empty(),
                "{}: needs `{}` with {} builds",
                e.id,
                e.needs,
                e.builds.len()
            );
            if e.needs == "on-path" {
                assert!(!e.program.contains('/'), "{}: a bare program name", e.id);
            }
        }
    }

    /// **Both darwin architectures resolve, each on its own machine.** The
    /// platform is passed rather than read for exactly this: one machine has to
    /// be able to answer for the other, or the arm64 developer ships an install
    /// path no Intel Mac was ever asked about.
    #[test]
    fn each_darwin_architecture_resolves_its_own_build() {
        let cursor = catalog()
            .entries
            .into_iter()
            .find(|e| e.id == "cursor")
            .expect("the registry lists Cursor");
        for platform in ["darwin-aarch64", "darwin-x86_64"] {
            let HostBuild::Ready(b) = build_for(&cursor, Some(platform)) else {
                panic!("{platform} resolves no build for Cursor");
            };
            assert!(b.archive.starts_with("https://"), "{platform}: {}", b.archive);
            assert!(b.archive.contains("darwin"), "{platform}: {}", b.archive);
            assert_eq!(b.cmd, "./dist-package/cursor-agent");
        }
        // And the two are not the same download, which is the thing a
        // host-independent lookup would have hidden.
        let arm = match build_for(&cursor, Some("darwin-aarch64")) {
            HostBuild::Ready(b) => b.archive.clone(),
            _ => unreachable!(),
        };
        let intel = match build_for(&cursor, Some("darwin-x86_64")) {
            HostBuild::Ready(b) => b.archive.clone(),
            _ => unreachable!(),
        };
        assert_ne!(arm, intel);
    }

    /// **An entry with no build for the host arch is unavailable, not offered.**
    /// `kimi` is the measured case: `darwin-aarch64` and both Linux targets, no
    /// `darwin-x86_64`. A row that fell back to any build would offer an Intel
    /// Mac a binary that cannot run on it.
    #[test]
    fn an_agent_with_no_build_for_this_architecture_is_unavailable_rather_than_offered() {
        let kimi = catalog()
            .entries
            .into_iter()
            .find(|e| e.id == "kimi")
            .expect("the registry lists Kimi");
        assert!(matches!(build_for(&kimi, Some("darwin-aarch64")), HostBuild::Ready(_)));
        assert!(matches!(build_for(&kimi, Some("darwin-x86_64")), HostBuild::NoBuildHere));

        // And the row says which of the two it is, since `build: None` alone is
        // also what every npx entry has.
        let adapters = crate::agents::registry();
        let row = row_for(kimi, adapters, Some("darwin-x86_64"));
        assert!(row.build.is_none());
        assert!(row.no_build_here, "unavailable here, not merely not installable");

        let npx = catalog().entries.into_iter().find(|e| e.needs == "npx").unwrap();
        let npx_row = row_for(npx, adapters, Some("darwin-x86_64"));
        assert!(npx_row.build.is_none());
        assert!(!npx_row.no_build_here, "an npx row is not an unsupported architecture");
    }

    /// Cursor is the entry the plan names, and it is now something Sway can
    /// fetch: an archive per platform, the path inside it, and the fact that this
    /// particular publisher supplies no checksum to check it against.
    #[test]
    fn the_catalog_offers_cursor_as_a_download_and_says_it_is_unverified() {
        let cursor = catalog()
            .entries
            .into_iter()
            .find(|e| e.id == "cursor")
            .expect("the registry lists Cursor");
        assert_eq!(cursor.command(), "cursor-agent acp");
        assert_eq!(cursor.needs, "install");
        let HostBuild::Ready(b) = build_for(&cursor, Some("darwin-aarch64")) else {
            panic!("no darwin build");
        };
        assert_eq!(b.args, vec!["acp".to_string()]);
        assert!(b.sha256.is_none(), "Cursor publishes none, and that stays visible");
    }

    /// The other half of the checksum story: a publisher that does supply one is
    /// carried through as a real hash rather than flattened into the same
    /// "unverified" as Cursor.
    #[test]
    fn a_publisher_that_supplies_a_checksum_has_it_carried_through() {
        let with_sums: Vec<String> = catalog()
            .entries
            .into_iter()
            .filter(|e| {
                matches!(build_for(e, Some("darwin-aarch64")), HostBuild::Ready(b) if b.sha256.is_some())
            })
            .map(|e| e.id)
            .collect();
        assert!(with_sums.contains(&"opencode".to_string()), "{with_sums:?}");
        for id in &with_sums {
            let e = catalog().entries.into_iter().find(|e| &e.id == id).unwrap();
            let HostBuild::Ready(b) = build_for(&e, Some("darwin-aarch64")) else { unreachable!() };
            let sha = b.sha256.clone().unwrap();
            assert_eq!(sha.len(), 64, "{id}: a sha256 is 64 hex characters, got {sha}");
            assert!(sha.chars().all(|c| c.is_ascii_hexdigit()), "{id}: {sha}");
        }
        // Measured 2026-08-14: some publish one and some do not, so neither the
        // verified nor the unverified path is dead code.
        let installable = catalog().entries.into_iter().filter(|e| !e.builds.is_empty()).count();
        assert!(with_sums.len() < installable, "{} of {installable}", with_sums.len());
    }

    /// **The published matrix is a prior, and it says so.** The capabilities on a
    /// row are the registry's own probe, carried under a name that names the
    /// prober, with the date and the source beside them. Nothing here is a tier:
    /// tiers live in `chatCapabilities.ts` and are keyed on transports Sway
    /// implements.
    #[test]
    fn published_capabilities_name_whose_measurement_they_are() {
        let c = catalog();
        let source = c.matrix_source.clone().expect("the registry publishes a matrix");
        assert!(source.source.contains(".protocol-matrix/latest.json"), "{}", source.source);
        assert!(source.probed_on.is_some(), "and the date it was probed");
        assert!(source.agents_probed > 0);

        let probed: Vec<&CatalogEntry> =
            c.entries.iter().filter(|e| e.published_capabilities.is_some()).collect();
        assert!(!probed.is_empty(), "some entries carry the matrix's answers");
        // A probe that says nothing is still a probe: `None` on a field is "the
        // matrix did not say", which is not the same as "the matrix said no".
        assert!(
            probed.iter().any(|e| e
                .published_capabilities
                .as_ref()
                .is_some_and(|p| p.session_list == Some(true))),
            "at least one agent the registry probed answers session/list"
        );
    }

    /// **The catalog still works when there is no matrix.** The file sits in a
    /// dot-directory covered by neither published schema, so an upstream that
    /// renames it, reshapes it or drops it must cost the catalogue its
    /// capabilities and nothing else. A prior that could stop the list from
    /// loading would not be optional.
    #[test]
    fn a_catalog_with_no_matrix_still_parses_and_still_lists_its_agents() {
        let without = r#"{
            "source": "https://github.com/agentclientprotocol/registry",
            "registry_commit": "abc",
            "generated_by": "dev/acp-catalog.mjs",
            "entries": [{
                "id": "x", "label": "X", "program": "npx", "args": ["-y", "x"], "needs": "npx"
            }]
        }"#;
        let c: AcpCatalog = serde_json::from_str(without).expect("parses without a matrix");
        assert!(c.matrix_source.is_none());
        assert_eq!(c.entries.len(), 1);
        assert!(c.entries[0].published_capabilities.is_none());
        assert!(c.entries[0].builds.is_empty());

        // And a reshaped one is the same outcome, because the generator writes
        // this field only from a shape it recognised.
        let row = row_for(c.entries[0].clone(), &[], Some("darwin-aarch64"));
        assert!(row.published_capabilities.is_none());
        assert!(!row.no_build_here, "no builds at all is not an unsupported architecture");
    }

    /// **A catalog entry claims no tier it did not earn, downloaded or not.**
    /// The row carries the registry's probe and the download, and nothing that
    /// reads as a measurement of Sway's: no `verified_against`, no transport, no
    /// tier. Installing changes where the binary is, not what anyone has tested.
    #[test]
    fn an_installable_row_is_still_an_untested_entry() {
        let json = serde_json::to_value(acp_catalog()).unwrap();
        let row = json
            .as_array()
            .unwrap()
            .iter()
            .find(|r| r["needs"] == "install")
            .expect("some rows are installable");
        for earned in ["verifiedAgainst", "verified_against", "tier", "transport", "capabilities"] {
            assert!(row.get(earned).is_none(), "an untested row carries no {earned}: {row}");
        }
        // What it does carry is the registry's own claim, under the registry's
        // own name.
        assert!(row.get("publishedCapabilities").is_some());
    }

    /// **The line between a catalog entry and a supported harness.**
    ///
    /// The catalog contributes nothing to the adapter registry, so nothing in it
    /// can reach Settings > Agents as a card, get a capability tier, or be
    /// launched. The agents that *are* supported are supported because a TOML
    /// ships for them, and the catalog says so rather than being the reason.
    #[test]
    fn a_catalog_entry_is_not_an_adapter() {
        let adapters: Vec<&str> = crate::agents::registry().iter().map(|a| a.id.as_str()).collect();
        let rows = acp_catalog();
        assert!(rows.len() > 30, "the catalog is the long list: {}", rows.len());

        // Far more entries than adapters: if the catalog were feeding the
        // registry, these two numbers would move together.
        assert!(
            rows.len() > adapters.len() * 5,
            "{} catalog rows against {} adapters",
            rows.len(),
            adapters.len()
        );

        // And the ones an adapter already covers say which, so the UI can offer
        // the measured harness instead of a second way to start the same agent.
        let covered: Vec<&str> = rows
            .iter()
            .filter(|r| r.covered_by.is_some())
            .map(|r| r.id.as_str())
            .collect();
        assert!(covered.contains(&"opencode"), "opencode ships an adapter: {covered:?}");
        assert!(covered.contains(&"gemini"), "gemini ships an adapter: {covered:?}");
        assert!(
            covered.contains(&"codex-acp"),
            "codex.toml launches this exact package: {covered:?}"
        );
        assert!(
            !covered.contains(&"cursor"),
            "cursor ships none, so it stays an untested entry: {covered:?}"
        );
    }

    /// **The regression `launch_identity` exists to stop.**
    ///
    /// `codex.toml` is the first bundled adapter whose chat binary is `npx`, and
    /// the match used to compare programs. That would have made every `npx` row
    /// in the registry - the bulk of it - read as "already covered by Codex", so
    /// the catalog would have quietly stopped offering agents Sway has never
    /// measured. A package runner names the runner, never the agent.
    #[test]
    fn a_package_runner_does_not_cover_every_agent_launched_through_it() {
        let adapters = crate::agents::registry();
        let rows: Vec<CatalogRow> = catalog()
            .entries
            .into_iter()
            .filter(|e| e.program == "npx")
            .map(|e| row_for(e, adapters, host_platform()))
            .collect();
        assert!(rows.len() > 5, "the registry is mostly npx launches: {}", rows.len());

        let wrongly_covered: Vec<&str> = rows
            .iter()
            .filter(|r| r.covered_by.as_deref() == Some("codex") && r.id != "codex-acp")
            .map(|r| r.id.as_str())
            .collect();
        assert!(
            wrongly_covered.is_empty(),
            "these are npx launches of other agents, not of Codex: {wrongly_covered:?}"
        );
    }

    /// The identity sees through the runner and past the pin, and leaves an
    /// ordinary binary alone.
    #[test]
    fn launch_identity_names_the_package_not_the_runner() {
        let args = |v: &[&str]| v.iter().map(|s| s.to_string()).collect::<Vec<_>>();
        assert_eq!(
            launch_identity("npx", &args(&["-y", "@agentclientprotocol/codex-acp@1.2.0"])),
            "@agentclientprotocol/codex-acp"
        );
        // A pinned adapter and a differently pinned registry row are one agent.
        assert_eq!(
            launch_identity("npx", &args(&["-y", "@agentclientprotocol/codex-acp@9.9.9"])),
            launch_identity("npx", &args(&["-y", "@agentclientprotocol/codex-acp"])),
        );
        // An unscoped package keeps its whole name when it carries no pin.
        assert_eq!(launch_identity("npx", &args(&["-y", "some-agent"])), "some-agent");
        assert_eq!(launch_identity("npx", &args(&["-y", "some-agent@2.0.0"])), "some-agent");
        // Not a runner: the program is the identity, args or not.
        assert_eq!(launch_identity("opencode", &args(&["acp"])), "opencode");
        // A runner with nothing to run degrades to itself rather than panicking.
        assert_eq!(launch_identity("npx", &args(&["-y"])), "npx");
    }

    /// The provenance command carries no entries, so a caller cannot render an
    /// unannotated list that looks like the annotated one. It is a separate type
    /// rather than the catalogue with a field cleared, which is what makes that
    /// structural instead of a line somebody could delete.
    #[test]
    fn the_provenance_command_carries_no_entries() {
        let json = serde_json::to_value(acp_catalog_source()).unwrap();
        assert!(json.get("entries").is_none(), "{json}");
        assert!(!acp_catalog_source().registry_commit.is_empty());
    }

    /// **The wire is camelCase, on every field the frontend reads.** The row used
    /// to flatten the file's own snake_case struct, so `registryVersion` in the
    /// TypeScript type was reading a key nothing sent. A mismatch like that is
    /// invisible until a field is actually used, which is exactly when the
    /// install controls started using several.
    #[test]
    fn every_field_the_frontend_reads_is_sent_in_the_shape_it_reads_it() {
        let rows = serde_json::to_value(acp_catalog()).unwrap();
        let row = rows
            .as_array()
            .unwrap()
            .iter()
            .find(|r| r["needs"] == "install")
            .expect("some rows are installable");
        for key in ["registryVersion", "coveredBy", "noBuildHere", "publishedCapabilities"] {
            assert!(row.get(key).is_some(), "no {key} on {row}");
        }
        assert!(row["build"]["sha256"].is_null() || row["build"]["sha256"].is_string());

        let source = serde_json::to_value(acp_catalog_source()).unwrap();
        for key in ["registryCommit", "generatedOn", "generatedBy", "hostPlatform"] {
            assert!(source.get(key).is_some(), "no {key} on {source}");
        }
        assert!(source["matrixSource"]["probedOn"].is_string());
    }

    /// **An agent the registry says is broken is not offered at all.**
    ///
    /// The catalogue's entries claim only "untested by Sway". A quarantined agent
    /// is a much stronger claim - the people curating the registry ran it and it
    /// failed - and putting one in the same list would launder that into the
    /// weaker one. Excluded, with the upstream's own reasons carried alongside so
    /// "why is X missing" has an answer.
    #[test]
    fn an_agent_the_registry_quarantines_is_not_offered() {
        let c = catalog();
        assert!(!c.quarantined.is_empty(), "the registry publishes a quarantine list");
        for (id, reason) in &c.quarantined {
            assert!(
                !c.entries.iter().any(|e| &e.id == id),
                "{id} is quarantined ({reason}) and must not be offered"
            );
            assert!(!reason.is_empty(), "{id}: quarantined for a stated reason");
        }
    }
}
