// GENERATED by scripts/gen-seti.mjs from VS Code's theme-seti. Do not edit by hand.
// Glyphs are Private Use Area chars rendered with the bundled `seti` webfont.
// `hue` names one of the 11 scale.* roles; the active theme supplies the value,
// so the file tree follows the theme instead of seti's dark variant.

export type SetiHue =
  | "red"
  | "green"
  | "blue"
  | "yellow"
  | "slate"
  | "orange"
  | "purple"
  | "pink"
  | "silver"
  | "steel"
  | "graphite";

export type SetiIcon = { glyph: string; hue: SetiHue };

export const fileNames: Record<string, SetiIcon> = {
  "mix": {
    "glyph": "",
    "hue": "red"
  },
  "karma.conf.js": {
    "glyph": "",
    "hue": "green"
  },
  "karma.conf.cjs": {
    "glyph": "",
    "hue": "green"
  },
  "karma.conf.mjs": {
    "glyph": "",
    "hue": "green"
  },
  "karma.conf.coffee": {
    "glyph": "",
    "hue": "green"
  },
  "readme.md": {
    "glyph": "",
    "hue": "blue"
  },
  "readme.txt": {
    "glyph": "",
    "hue": "blue"
  },
  "readme": {
    "glyph": "",
    "hue": "blue"
  },
  "changelog.md": {
    "glyph": "",
    "hue": "blue"
  },
  "changelog.txt": {
    "glyph": "",
    "hue": "blue"
  },
  "changelog": {
    "glyph": "",
    "hue": "blue"
  },
  "changes.md": {
    "glyph": "",
    "hue": "blue"
  },
  "changes.txt": {
    "glyph": "",
    "hue": "blue"
  },
  "changes": {
    "glyph": "",
    "hue": "blue"
  },
  "version.md": {
    "glyph": "",
    "hue": "blue"
  },
  "version.txt": {
    "glyph": "",
    "hue": "blue"
  },
  "version": {
    "glyph": "",
    "hue": "blue"
  },
  "mvnw": {
    "glyph": "",
    "hue": "red"
  },
  "pom.xml": {
    "glyph": "",
    "hue": "red"
  },
  "tsconfig.json": {
    "glyph": "",
    "hue": "blue"
  },
  "vite.config.js": {
    "glyph": "",
    "hue": "yellow"
  },
  "vite.config.ts": {
    "glyph": "",
    "hue": "yellow"
  },
  "vite.config.mjs": {
    "glyph": "",
    "hue": "yellow"
  },
  "vite.config.mts": {
    "glyph": "",
    "hue": "yellow"
  },
  "vite.config.cjs": {
    "glyph": "",
    "hue": "yellow"
  },
  "vite.config.cts": {
    "glyph": "",
    "hue": "yellow"
  },
  "swagger.json": {
    "glyph": "",
    "hue": "green"
  },
  "swagger.yml": {
    "glyph": "",
    "hue": "green"
  },
  "swagger.yaml": {
    "glyph": "",
    "hue": "green"
  },
  "mime.types": {
    "glyph": "",
    "hue": "slate"
  },
  "jenkinsfile": {
    "glyph": "",
    "hue": "red"
  },
  "babel.config.js": {
    "glyph": "",
    "hue": "yellow"
  },
  "babel.config.json": {
    "glyph": "",
    "hue": "yellow"
  },
  "babel.config.cjs": {
    "glyph": "",
    "hue": "yellow"
  },
  "build": {
    "glyph": "",
    "hue": "green"
  },
  "build.bazel": {
    "glyph": "",
    "hue": "green"
  },
  "workspace": {
    "glyph": "",
    "hue": "green"
  },
  "workspace.bazel": {
    "glyph": "",
    "hue": "green"
  },
  "bower.json": {
    "glyph": "",
    "hue": "orange"
  },
  "docker-healthcheck": {
    "glyph": "",
    "hue": "green"
  },
  "eslint.config.js": {
    "glyph": "",
    "hue": "purple"
  },
  "firebase.json": {
    "glyph": "",
    "hue": "orange"
  },
  "geckodriver": {
    "glyph": "",
    "hue": "orange"
  },
  "gruntfile.js": {
    "glyph": "",
    "hue": "orange"
  },
  "gruntfile.babel.js": {
    "glyph": "",
    "hue": "orange"
  },
  "gruntfile.coffee": {
    "glyph": "",
    "hue": "orange"
  },
  "gulpfile": {
    "glyph": "",
    "hue": "red"
  },
  "gulpfile.js": {
    "glyph": "",
    "hue": "red"
  },
  "ionic.config.json": {
    "glyph": "",
    "hue": "blue"
  },
  "ionic.project": {
    "glyph": "",
    "hue": "blue"
  },
  "platformio.ini": {
    "glyph": "",
    "hue": "orange"
  },
  "rollup.config.js": {
    "glyph": "",
    "hue": "red"
  },
  "sass-lint.yml": {
    "glyph": "",
    "hue": "pink"
  },
  "stylelint.config.js": {
    "glyph": "",
    "hue": "silver"
  },
  "stylelint.config.cjs": {
    "glyph": "",
    "hue": "silver"
  },
  "stylelint.config.mjs": {
    "glyph": "",
    "hue": "silver"
  },
  "yarn.clean": {
    "glyph": "",
    "hue": "blue"
  },
  "yarn.lock": {
    "glyph": "",
    "hue": "blue"
  },
  "webpack.config.js": {
    "glyph": "",
    "hue": "blue"
  },
  "webpack.config.cjs": {
    "glyph": "",
    "hue": "blue"
  },
  "webpack.config.mjs": {
    "glyph": "",
    "hue": "blue"
  },
  "webpack.config.ts": {
    "glyph": "",
    "hue": "blue"
  },
  "webpack.config.build.js": {
    "glyph": "",
    "hue": "blue"
  },
  "webpack.config.build.cjs": {
    "glyph": "",
    "hue": "blue"
  },
  "webpack.config.build.mjs": {
    "glyph": "",
    "hue": "blue"
  },
  "webpack.config.build.ts": {
    "glyph": "",
    "hue": "blue"
  },
  "webpack.common.js": {
    "glyph": "",
    "hue": "blue"
  },
  "webpack.common.cjs": {
    "glyph": "",
    "hue": "blue"
  },
  "webpack.common.mjs": {
    "glyph": "",
    "hue": "blue"
  },
  "webpack.common.ts": {
    "glyph": "",
    "hue": "blue"
  },
  "webpack.dev.js": {
    "glyph": "",
    "hue": "blue"
  },
  "webpack.dev.cjs": {
    "glyph": "",
    "hue": "blue"
  },
  "webpack.dev.mjs": {
    "glyph": "",
    "hue": "blue"
  },
  "webpack.dev.ts": {
    "glyph": "",
    "hue": "blue"
  },
  "webpack.prod.js": {
    "glyph": "",
    "hue": "blue"
  },
  "webpack.prod.cjs": {
    "glyph": "",
    "hue": "blue"
  },
  "webpack.prod.mjs": {
    "glyph": "",
    "hue": "blue"
  },
  "webpack.prod.ts": {
    "glyph": "",
    "hue": "blue"
  },
  "license": {
    "glyph": "",
    "hue": "yellow"
  },
  "licence": {
    "glyph": "",
    "hue": "yellow"
  },
  "license.txt": {
    "glyph": "",
    "hue": "yellow"
  },
  "licence.txt": {
    "glyph": "",
    "hue": "yellow"
  },
  "license.md": {
    "glyph": "",
    "hue": "yellow"
  },
  "licence.md": {
    "glyph": "",
    "hue": "yellow"
  },
  "copying": {
    "glyph": "",
    "hue": "yellow"
  },
  "copying.txt": {
    "glyph": "",
    "hue": "yellow"
  },
  "copying.md": {
    "glyph": "",
    "hue": "yellow"
  },
  "compiling": {
    "glyph": "",
    "hue": "orange"
  },
  "compiling.txt": {
    "glyph": "",
    "hue": "orange"
  },
  "compiling.md": {
    "glyph": "",
    "hue": "orange"
  },
  "contributing": {
    "glyph": "",
    "hue": "red"
  },
  "contributing.txt": {
    "glyph": "",
    "hue": "red"
  },
  "contributing.md": {
    "glyph": "",
    "hue": "red"
  },
  "qmakefile": {
    "glyph": "",
    "hue": "purple"
  },
  "omakefile": {
    "glyph": "",
    "hue": "slate"
  },
  "cmakelists.txt": {
    "glyph": "",
    "hue": "blue"
  },
  "procfile": {
    "glyph": "",
    "hue": "purple"
  },
  "todo": {
    "glyph": "",
    "hue": "silver"
  },
  "todo.txt": {
    "glyph": "",
    "hue": "silver"
  },
  "todo.md": {
    "glyph": "",
    "hue": "silver"
  },
  "npm-debug.log": {
    "glyph": "",
    "hue": "steel"
  }
};

export const extensions: Record<string, SetiIcon> = {
  "ts": {
    "glyph": "",
    "hue": "blue"
  },
  "mts": {
    "glyph": "",
    "hue": "blue"
  },
  "cts": {
    "glyph": "",
    "hue": "blue"
  },
  "d.ts": {
    "glyph": "",
    "hue": "blue"
  },
  "tsx": {
    "glyph": "",
    "hue": "blue"
  },
  "js": {
    "glyph": "",
    "hue": "yellow"
  },
  "mjs": {
    "glyph": "",
    "hue": "yellow"
  },
  "cjs": {
    "glyph": "",
    "hue": "yellow"
  },
  "jsx": {
    "glyph": "",
    "hue": "blue"
  },
  "json": {
    "glyph": "",
    "hue": "yellow"
  },
  "jsonc": {
    "glyph": "",
    "hue": "yellow"
  },
  "jsonl": {
    "glyph": "",
    "hue": "yellow"
  },
  "md": {
    "glyph": "",
    "hue": "blue"
  },
  "markdown": {
    "glyph": "",
    "hue": "blue"
  },
  "html": {
    "glyph": "",
    "hue": "orange"
  },
  "htm": {
    "glyph": "",
    "hue": "orange"
  },
  "css": {
    "glyph": "",
    "hue": "blue"
  },
  "scss": {
    "glyph": "",
    "hue": "pink"
  },
  "sass": {
    "glyph": "",
    "hue": "pink"
  },
  "less": {
    "glyph": "",
    "hue": "blue"
  },
  "styl": {
    "glyph": "",
    "hue": "green"
  },
  "py": {
    "glyph": "",
    "hue": "blue"
  },
  "pyw": {
    "glyph": "",
    "hue": "blue"
  },
  "pyi": {
    "glyph": "",
    "hue": "blue"
  },
  "rs": {
    "glyph": "",
    "hue": "slate"
  },
  "go": {
    "glyph": "",
    "hue": "blue"
  },
  "yaml": {
    "glyph": "",
    "hue": "purple"
  },
  "yml": {
    "glyph": "",
    "hue": "purple"
  },
  "sh": {
    "glyph": "",
    "hue": "green"
  },
  "bash": {
    "glyph": "",
    "hue": "green"
  },
  "zsh": {
    "glyph": "",
    "hue": "green"
  },
  "c": {
    "glyph": "",
    "hue": "blue"
  },
  "h": {
    "glyph": "",
    "hue": "purple"
  },
  "cpp": {
    "glyph": "",
    "hue": "blue"
  },
  "cc": {
    "glyph": "",
    "hue": "blue"
  },
  "cxx": {
    "glyph": "",
    "hue": "blue"
  },
  "hpp": {
    "glyph": "",
    "hue": "purple"
  },
  "hh": {
    "glyph": "",
    "hue": "purple"
  },
  "cs": {
    "glyph": "",
    "hue": "blue"
  },
  "java": {
    "glyph": "",
    "hue": "red"
  },
  "kt": {
    "glyph": "",
    "hue": "orange"
  },
  "kts": {
    "glyph": "",
    "hue": "orange"
  },
  "swift": {
    "glyph": "",
    "hue": "orange"
  },
  "rb": {
    "glyph": "",
    "hue": "red"
  },
  "php": {
    "glyph": "",
    "hue": "purple"
  },
  "pl": {
    "glyph": "",
    "hue": "blue"
  },
  "pm": {
    "glyph": "",
    "hue": "blue"
  },
  "lua": {
    "glyph": "",
    "hue": "blue"
  },
  "r": {
    "glyph": "",
    "hue": "blue"
  },
  "dart": {
    "glyph": "",
    "hue": "blue"
  },
  "ex": {
    "glyph": "",
    "hue": "purple"
  },
  "exs": {
    "glyph": "",
    "hue": "purple"
  },
  "elm": {
    "glyph": "",
    "hue": "blue"
  },
  "hs": {
    "glyph": "",
    "hue": "purple"
  },
  "ml": {
    "glyph": "",
    "hue": "orange"
  },
  "mli": {
    "glyph": "",
    "hue": "orange"
  },
  "clj": {
    "glyph": "",
    "hue": "green"
  },
  "cljs": {
    "glyph": "",
    "hue": "green"
  },
  "cljc": {
    "glyph": "",
    "hue": "green"
  },
  "coffee": {
    "glyph": "",
    "hue": "yellow"
  },
  "fs": {
    "glyph": "",
    "hue": "blue"
  },
  "fsi": {
    "glyph": "",
    "hue": "blue"
  },
  "fsx": {
    "glyph": "",
    "hue": "blue"
  },
  "groovy": {
    "glyph": "",
    "hue": "green"
  },
  "jl": {
    "glyph": "",
    "hue": "purple"
  },
  "m": {
    "glyph": "",
    "hue": "yellow"
  },
  "mm": {
    "glyph": "",
    "hue": "yellow"
  },
  "ps1": {
    "glyph": "",
    "hue": "blue"
  },
  "psm1": {
    "glyph": "",
    "hue": "blue"
  },
  "psd1": {
    "glyph": "",
    "hue": "blue"
  },
  "sql": {
    "glyph": "",
    "hue": "pink"
  },
  "xml": {
    "glyph": "",
    "hue": "orange"
  },
  "vue": {
    "glyph": "",
    "hue": "green"
  },
  "tex": {
    "glyph": "",
    "hue": "yellow"
  },
  "latex": {
    "glyph": "",
    "hue": "blue"
  },
  "bat": {
    "glyph": "",
    "hue": "blue"
  },
  "cmd": {
    "glyph": "",
    "hue": "blue"
  },
  "properties": {
    "glyph": "",
    "hue": "slate"
  },
  "ini": {
    "glyph": "",
    "hue": "slate"
  },
  "cfg": {
    "glyph": "",
    "hue": "slate"
  },
  "tf": {
    "glyph": "",
    "hue": "purple"
  },
  "tfvars": {
    "glyph": "",
    "hue": "purple"
  },
  "bicep": {
    "glyph": "",
    "hue": "blue"
  },
  "vala": {
    "glyph": "",
    "hue": "slate"
  },
  "hx": {
    "glyph": "",
    "hue": "orange"
  },
  "haml": {
    "glyph": "",
    "hue": "red"
  },
  "jade": {
    "glyph": "",
    "hue": "red"
  },
  "pug": {
    "glyph": "",
    "hue": "red"
  },
  "gradle": {
    "glyph": "",
    "hue": "blue"
  },
  "gd": {
    "glyph": "",
    "hue": "blue"
  },
  "res": {
    "glyph": "",
    "hue": "red"
  },
  "resi": {
    "glyph": "",
    "hue": "pink"
  },
  "bsl": {
    "glyph": "",
    "hue": "red"
  },
  "mdo": {
    "glyph": "",
    "hue": "red"
  },
  "cls": {
    "glyph": "",
    "hue": "blue"
  },
  "apex": {
    "glyph": "",
    "hue": "blue"
  },
  "asm": {
    "glyph": "",
    "hue": "red"
  },
  "s": {
    "glyph": "",
    "hue": "red"
  },
  "bzl": {
    "glyph": "",
    "hue": "green"
  },
  "bazel": {
    "glyph": "",
    "hue": "green"
  },
  "build": {
    "glyph": "",
    "hue": "green"
  },
  "workspace": {
    "glyph": "",
    "hue": "green"
  },
  "bazelignore": {
    "glyph": "",
    "hue": "green"
  },
  "bazelversion": {
    "glyph": "",
    "hue": "green"
  },
  "aspx": {
    "glyph": "",
    "hue": "blue"
  },
  "ascx": {
    "glyph": "",
    "hue": "green"
  },
  "asax": {
    "glyph": "",
    "hue": "yellow"
  },
  "master": {
    "glyph": "",
    "hue": "yellow"
  },
  "hxx": {
    "glyph": "",
    "hue": "purple"
  },
  "h++": {
    "glyph": "",
    "hue": "purple"
  },
  "edn": {
    "glyph": "",
    "hue": "blue"
  },
  "cfc": {
    "glyph": "",
    "hue": "blue"
  },
  "cfm": {
    "glyph": "",
    "hue": "blue"
  },
  "litcoffee": {
    "glyph": "",
    "hue": "yellow"
  },
  "config": {
    "glyph": "",
    "hue": "slate"
  },
  "cr": {
    "glyph": "",
    "hue": "silver"
  },
  "ecr": {
    "glyph": "",
    "hue": "silver"
  },
  "slang": {
    "glyph": "",
    "hue": "silver"
  },
  "cson": {
    "glyph": "",
    "hue": "yellow"
  },
  "css.map": {
    "glyph": "",
    "hue": "blue"
  },
  "sss": {
    "glyph": "",
    "hue": "blue"
  },
  "csv": {
    "glyph": "",
    "hue": "green"
  },
  "xls": {
    "glyph": "",
    "hue": "green"
  },
  "xlsx": {
    "glyph": "",
    "hue": "green"
  },
  "cuh": {
    "glyph": "",
    "hue": "purple"
  },
  "hu": {
    "glyph": "",
    "hue": "purple"
  },
  "cake": {
    "glyph": "",
    "hue": "red"
  },
  "ctp": {
    "glyph": "",
    "hue": "red"
  },
  "d": {
    "glyph": "",
    "hue": "red"
  },
  "doc": {
    "glyph": "",
    "hue": "blue"
  },
  "docx": {
    "glyph": "",
    "hue": "blue"
  },
  "ejs": {
    "glyph": "",
    "hue": "yellow"
  },
  "ico": {
    "glyph": "",
    "hue": "yellow"
  },
  "gitconfig": {
    "glyph": "",
    "hue": "steel"
  },
  "gitkeep": {
    "glyph": "",
    "hue": "steel"
  },
  "gitattributes": {
    "glyph": "",
    "hue": "steel"
  },
  "gitmodules": {
    "glyph": "",
    "hue": "steel"
  },
  "slide": {
    "glyph": "",
    "hue": "blue"
  },
  "article": {
    "glyph": "",
    "hue": "blue"
  },
  "godot": {
    "glyph": "",
    "hue": "red"
  },
  "tres": {
    "glyph": "",
    "hue": "yellow"
  },
  "tscn": {
    "glyph": "",
    "hue": "purple"
  },
  "gsp": {
    "glyph": "",
    "hue": "green"
  },
  "gql": {
    "glyph": "",
    "hue": "pink"
  },
  "graphql": {
    "glyph": "",
    "hue": "pink"
  },
  "graphqls": {
    "glyph": "",
    "hue": "pink"
  },
  "hack": {
    "glyph": "",
    "hue": "orange"
  },
  "lhs": {
    "glyph": "",
    "hue": "purple"
  },
  "hxs": {
    "glyph": "",
    "hue": "yellow"
  },
  "hxp": {
    "glyph": "",
    "hue": "blue"
  },
  "hxml": {
    "glyph": "",
    "hue": "purple"
  },
  "class": {
    "glyph": "",
    "hue": "blue"
  },
  "classpath": {
    "glyph": "",
    "hue": "red"
  },
  "js.map": {
    "glyph": "",
    "hue": "yellow"
  },
  "cjs.map": {
    "glyph": "",
    "hue": "yellow"
  },
  "mjs.map": {
    "glyph": "",
    "hue": "yellow"
  },
  "spec.js": {
    "glyph": "",
    "hue": "orange"
  },
  "spec.cjs": {
    "glyph": "",
    "hue": "orange"
  },
  "spec.mjs": {
    "glyph": "",
    "hue": "orange"
  },
  "test.js": {
    "glyph": "",
    "hue": "orange"
  },
  "test.cjs": {
    "glyph": "",
    "hue": "orange"
  },
  "test.mjs": {
    "glyph": "",
    "hue": "orange"
  },
  "es": {
    "glyph": "",
    "hue": "yellow"
  },
  "es5": {
    "glyph": "",
    "hue": "yellow"
  },
  "es7": {
    "glyph": "",
    "hue": "yellow"
  },
  "jinja": {
    "glyph": "",
    "hue": "red"
  },
  "jinja2": {
    "glyph": "",
    "hue": "red"
  },
  "liquid": {
    "glyph": "",
    "hue": "green"
  },
  "ls": {
    "glyph": "",
    "hue": "blue"
  },
  "argdown": {
    "glyph": "",
    "hue": "blue"
  },
  "ad": {
    "glyph": "",
    "hue": "blue"
  },
  "mustache": {
    "glyph": "",
    "hue": "orange"
  },
  "stache": {
    "glyph": "",
    "hue": "orange"
  },
  "nim": {
    "glyph": "",
    "hue": "yellow"
  },
  "nims": {
    "glyph": "",
    "hue": "yellow"
  },
  "github-issues": {
    "glyph": "",
    "hue": "silver"
  },
  "ipynb": {
    "glyph": "",
    "hue": "blue"
  },
  "njk": {
    "glyph": "",
    "hue": "green"
  },
  "nunjucks": {
    "glyph": "",
    "hue": "green"
  },
  "nunjs": {
    "glyph": "",
    "hue": "green"
  },
  "nunj": {
    "glyph": "",
    "hue": "green"
  },
  "njs": {
    "glyph": "",
    "hue": "green"
  },
  "nj": {
    "glyph": "",
    "hue": "green"
  },
  "npm-debug.log": {
    "glyph": "",
    "hue": "steel"
  },
  "npmignore": {
    "glyph": "",
    "hue": "red"
  },
  "npmrc": {
    "glyph": "",
    "hue": "red"
  },
  "cmx": {
    "glyph": "",
    "hue": "orange"
  },
  "cmxa": {
    "glyph": "",
    "hue": "orange"
  },
  "odata": {
    "glyph": "",
    "hue": "orange"
  },
  "php.inc": {
    "glyph": "",
    "hue": "purple"
  },
  "pipeline": {
    "glyph": "",
    "hue": "orange"
  },
  "pddl": {
    "glyph": "",
    "hue": "purple"
  },
  "plan": {
    "glyph": "",
    "hue": "green"
  },
  "happenings": {
    "glyph": "",
    "hue": "blue"
  },
  "prisma": {
    "glyph": "",
    "hue": "blue"
  },
  "pp": {
    "glyph": "",
    "hue": "yellow"
  },
  "epp": {
    "glyph": "",
    "hue": "yellow"
  },
  "purs": {
    "glyph": "",
    "hue": "silver"
  },
  "spec.jsx": {
    "glyph": "",
    "hue": "orange"
  },
  "test.jsx": {
    "glyph": "",
    "hue": "orange"
  },
  "cjsx": {
    "glyph": "",
    "hue": "blue"
  },
  "spec.tsx": {
    "glyph": "",
    "hue": "orange"
  },
  "test.tsx": {
    "glyph": "",
    "hue": "orange"
  },
  "re": {
    "glyph": "",
    "hue": "red"
  },
  "rmd": {
    "glyph": "",
    "hue": "blue"
  },
  "erb": {
    "glyph": "",
    "hue": "red"
  },
  "erb.html": {
    "glyph": "",
    "hue": "red"
  },
  "html.erb": {
    "glyph": "",
    "hue": "red"
  },
  "springbeans": {
    "glyph": "",
    "hue": "green"
  },
  "slim": {
    "glyph": "",
    "hue": "orange"
  },
  "smarty.tpl": {
    "glyph": "",
    "hue": "yellow"
  },
  "tpl": {
    "glyph": "",
    "hue": "yellow"
  },
  "sbt": {
    "glyph": "",
    "hue": "blue"
  },
  "scala": {
    "glyph": "",
    "hue": "red"
  },
  "sol": {
    "glyph": "",
    "hue": "blue"
  },
  "svelte": {
    "glyph": "",
    "hue": "red"
  },
  "soql": {
    "glyph": "",
    "hue": "blue"
  },
  "tf.json": {
    "glyph": "",
    "hue": "purple"
  },
  "tfvars.json": {
    "glyph": "",
    "hue": "purple"
  },
  "dtx": {
    "glyph": "",
    "hue": "orange"
  },
  "ins": {
    "glyph": "",
    "hue": "silver"
  },
  "toml": {
    "glyph": "",
    "hue": "slate"
  },
  "twig": {
    "glyph": "",
    "hue": "green"
  },
  "spec.ts": {
    "glyph": "",
    "hue": "orange"
  },
  "test.ts": {
    "glyph": "",
    "hue": "orange"
  },
  "vapi": {
    "glyph": "",
    "hue": "slate"
  },
  "component": {
    "glyph": "",
    "hue": "orange"
  },
  "wasm": {
    "glyph": "",
    "hue": "purple"
  },
  "wat": {
    "glyph": "",
    "hue": "purple"
  },
  "pro": {
    "glyph": "",
    "hue": "orange"
  },
  "zig": {
    "glyph": "",
    "hue": "orange"
  },
  "jar": {
    "glyph": "",
    "hue": "red"
  },
  "zip": {
    "glyph": "",
    "hue": "slate"
  },
  "wgt": {
    "glyph": "",
    "hue": "blue"
  },
  "ai": {
    "glyph": "",
    "hue": "yellow"
  },
  "psd": {
    "glyph": "",
    "hue": "blue"
  },
  "pdf": {
    "glyph": "",
    "hue": "red"
  },
  "eot": {
    "glyph": "",
    "hue": "red"
  },
  "ttf": {
    "glyph": "",
    "hue": "red"
  },
  "woff": {
    "glyph": "",
    "hue": "red"
  },
  "woff2": {
    "glyph": "",
    "hue": "red"
  },
  "otf": {
    "glyph": "",
    "hue": "red"
  },
  "avif": {
    "glyph": "",
    "hue": "purple"
  },
  "gif": {
    "glyph": "",
    "hue": "purple"
  },
  "jpg": {
    "glyph": "",
    "hue": "purple"
  },
  "jpeg": {
    "glyph": "",
    "hue": "purple"
  },
  "png": {
    "glyph": "",
    "hue": "purple"
  },
  "pxm": {
    "glyph": "",
    "hue": "purple"
  },
  "svg": {
    "glyph": "",
    "hue": "purple"
  },
  "svgx": {
    "glyph": "",
    "hue": "purple"
  },
  "tiff": {
    "glyph": "",
    "hue": "purple"
  },
  "webp": {
    "glyph": "",
    "hue": "purple"
  },
  "sublime-project": {
    "glyph": "",
    "hue": "orange"
  },
  "sublime-workspace": {
    "glyph": "",
    "hue": "orange"
  },
  "mov": {
    "glyph": "",
    "hue": "pink"
  },
  "ogv": {
    "glyph": "",
    "hue": "pink"
  },
  "webm": {
    "glyph": "",
    "hue": "pink"
  },
  "avi": {
    "glyph": "",
    "hue": "pink"
  },
  "mpg": {
    "glyph": "",
    "hue": "pink"
  },
  "mp4": {
    "glyph": "",
    "hue": "pink"
  },
  "mp3": {
    "glyph": "",
    "hue": "purple"
  },
  "ogg": {
    "glyph": "",
    "hue": "purple"
  },
  "wav": {
    "glyph": "",
    "hue": "purple"
  },
  "flac": {
    "glyph": "",
    "hue": "purple"
  },
  "3ds": {
    "glyph": "",
    "hue": "blue"
  },
  "3dm": {
    "glyph": "",
    "hue": "blue"
  },
  "stl": {
    "glyph": "",
    "hue": "blue"
  },
  "obj": {
    "glyph": "",
    "hue": "blue"
  },
  "dae": {
    "glyph": "",
    "hue": "blue"
  },
  "babelrc": {
    "glyph": "",
    "hue": "yellow"
  },
  "babelrc.js": {
    "glyph": "",
    "hue": "yellow"
  },
  "babelrc.cjs": {
    "glyph": "",
    "hue": "yellow"
  },
  "bazelrc": {
    "glyph": "",
    "hue": "graphite"
  },
  "bowerrc": {
    "glyph": "",
    "hue": "orange"
  },
  "dockerignore": {
    "glyph": "",
    "hue": "graphite"
  },
  "codeclimate.yml": {
    "glyph": "",
    "hue": "green"
  },
  "eslintrc": {
    "glyph": "",
    "hue": "purple"
  },
  "eslintrc.js": {
    "glyph": "",
    "hue": "purple"
  },
  "eslintrc.cjs": {
    "glyph": "",
    "hue": "purple"
  },
  "eslintrc.yaml": {
    "glyph": "",
    "hue": "purple"
  },
  "eslintrc.yml": {
    "glyph": "",
    "hue": "purple"
  },
  "eslintrc.json": {
    "glyph": "",
    "hue": "purple"
  },
  "eslintignore": {
    "glyph": "",
    "hue": "graphite"
  },
  "firebaserc": {
    "glyph": "",
    "hue": "orange"
  },
  "gitlab-ci.yml": {
    "glyph": "",
    "hue": "orange"
  },
  "jshintrc": {
    "glyph": "",
    "hue": "blue"
  },
  "jscsrc": {
    "glyph": "",
    "hue": "blue"
  },
  "stylelintrc": {
    "glyph": "",
    "hue": "silver"
  },
  "stylelintrc.json": {
    "glyph": "",
    "hue": "silver"
  },
  "stylelintrc.yaml": {
    "glyph": "",
    "hue": "silver"
  },
  "stylelintrc.yml": {
    "glyph": "",
    "hue": "silver"
  },
  "stylelintrc.js": {
    "glyph": "",
    "hue": "silver"
  },
  "stylelintignore": {
    "glyph": "",
    "hue": "graphite"
  },
  "direnv": {
    "glyph": "",
    "hue": "slate"
  },
  "static": {
    "glyph": "",
    "hue": "slate"
  },
  "slugignore": {
    "glyph": "",
    "hue": "slate"
  },
  "tmp": {
    "glyph": "",
    "hue": "slate"
  },
  "htaccess": {
    "glyph": "",
    "hue": "slate"
  },
  "key": {
    "glyph": "",
    "hue": "green"
  },
  "cert": {
    "glyph": "",
    "hue": "green"
  },
  "cer": {
    "glyph": "",
    "hue": "green"
  },
  "crt": {
    "glyph": "",
    "hue": "green"
  },
  "pem": {
    "glyph": "",
    "hue": "green"
  },
  "ds_store": {
    "glyph": "",
    "hue": "steel"
  }
};

export const defaultIcon: SetiIcon = {"glyph":"","hue":"silver"};
